function [GMi,plot_gmi] = Plot_Mi( Mi )
%Plot graph of one transition prob matrix
% Mi one probability matrix. Usually generated by the following command
%    prior to calling this routine
%    Mi = cell2mat(MMatrixCell(i));
%
%

nodenames = {'0000', '1000', '0100', '0010',...
    '0001', '1100', '1010', '1001', ...
    '0110', '0101', '0011', '1110', ...
    '1101', '1011', '0111', '1111'};
%
%   Generate the directed graph first
%   Calculate Edge LineWidths proportional to their weights

    GMi = digraph(Mi,nodenames,'OmitSelfloops');
    GMi.Edges.LWidths = 7*GMi.Edges.Weight/max(GMi.Edges.Weight);

%
%   Plot directed graph. Adjust some of the properties 
%
    plot_gmi = plot(GMi,'Layout','force','EdgeLabel',GMi.Edges.Weight);
    plot_gmi.NodeColor = 'red';
    plot_gmi.LineWidth = GMi.Edges.LWidths;
    plot_gmi.ArrowSize = 17;
    plot_gmi.EdgeColor = [0.0 0.4 0.7];
end

