function [ GMi, pgm] = Plot_Mk( MMatrixCell )
% Plot_Mk Plot all the transition matrices generated by TimeMachine
%
% MMatrixCell is the cell matrix generated in TimeMachine

nmat = length(MMatrixCell);
nodenames = {'0000', '1000', '0100', '0010',...
    '0001', '1100', '1010', '1001', ...
    '0110', '0101', '0011', '1110', ...
    '1101', '1011', '0111', '1111'};

%
%  Loop over all the transition prob matrices stored in MMatrixCell
%
for i=1:nmat
    Mi = cell2mat(MMatrixCell(i)); % First convert cell to matrix
%
%   Generate the directed graph first
%   Calculate Edge LineWidths proportional to their weights

    GMi = digraph(Mi,nodenames,'OmitSelfloops'); 
    GMi.Edges.LWidths = 7*GMi.Edges.Weight/max(GMi.Edges.Weight);
%
%   Plot directed graph. Adjust some of the properties 
%   Save the plot handle in array for later reference

    pgm(i) = plot(GMi,'Layout','force','EdgeLabel',GMi.Edges.Weight);
    pgm(i).NodeColor = 'red';
    pgm(i).LineWidth = GMi.Edges.LWidths;
    pgm(i).ArrowSize = 17;
    pgm(i).EdgeColor = [0.0 0.4 0.7];
end

end
